[tool.poetry]
name = "edu-but"
version = "0.1.0"
description = "Complex Layers experiments for high-dimensional sparse classification"
authors = ["Tomasz Łukaszuk <t.lukaszuk@pb.edu.pl>","Jerzy Krawczuk <j.krawczuk@pb.edu.pl>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "edu", from = "src" }]

[tool.poetry.dependencies]
python = "^3.13"
pandas = "^2.3.3"
matplotlib = "^3.10.7"
scikit-learn = "^1.7.1"
numpy = "^2.4.2"
tqdm = "^4.67.1"
scipy = "^1.16.3"

[tool.poetry.group.dev.dependencies]
ipykernel = "^7.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
